# Generated by Django 5.1.2 on 2024-11-10 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab2_HW_Shadrina', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='is_submitted',
            field=models.BooleanField(default=False),
        ),
    ]
