apiVersion: v1
kind: Service
metadata:
  name: hwboard-service
spec:
  type: NodePort
  selector:
    app: hwboard
  ports:
    - name: http
      port: 8000
      targetPort: 8000
      nodePort: 30008